In [2]:
print('#numpy ? - matrix - fast -\nfixed size,\nContinuous memory,\n')

#numpy ? - matrix - fast -
fixed size,
Continuous memory,



In [6]:
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


In [9]:
b=np.array([[9,4,3,0,6],[1,7,2,2,8]])
print(b)

[[9 4 3 0 6]
 [1 7 2 2 8]]


In [10]:
a.ndim # dimention

1

In [11]:
b.shape

(2, 5)

In [12]:
b.itemsize #

4

In [14]:
b.nbytes

40

In [17]:
c= np.array([[1,2,2,3,4,5,6],[5,6,6,5,5,7,8]])
print(c)

[[1 2 2 3 4 5 6]
 [5 6 6 5 5 7 8]]


In [19]:
c[1,5]

7