In [3]:
import numpy as np

In [8]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,8]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  8]]


In [12]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6]
 [ 7  8  2 10 11  8]]


In [9]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
b[0,1,1]  # 0th row of 1st diamantion, 
            # 1th row of 2nd diamention,
            # 1th row of 3rd diamention

4

In [11]:
b[:,1,:]

array([[3, 4],
       [7, 8]])