In [2]:
import numpy as np

In [8]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,8]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  8]]


In [12]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6]
 [ 7  8  2 10 11  8]]
