In [3]:
import numpy as np

In [21]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,8]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  8]]


In [12]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6]
 [ 7  8  2 10 11  8]]


In [9]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
b[0,1,1]  # 0th row of 1st diamantion, 
            # 1th row of 2nd diamention,
            # 1th row of 3rd diamention

4

In [11]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [13]:
b[1,0,:]=[96,45]
print(b)

[[[ 1  2]
  [ 3  4]]

 [[96 45]
  [ 7  8]]]


In [15]:
b[:,1,:]=[33,55]
print(b)

[[[ 1  2]
  [33 55]]

 [[96 45]
  [33 55]]]


In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
np.full((2,2),66)

array([[66, 66],
       [66, 66]])

In [22]:
print(a)
np.full_like(a,9)  # make an array with the size of "a"

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  8]]


array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [23]:
np.random.rand(4,2)

array([[0.84848413, 0.98367456],
       [0.09652498, 0.74181714],
       [0.01514478, 0.61379293],
       [0.97066094, 0.20821788]])

In [24]:

np.random.rand(4,2,3)


array([[[0.40428582, 0.55002094, 0.11254916],
        [0.6921439 , 0.83256123, 0.25009699]],

       [[0.01824255, 0.96192931, 0.33366765],
        [0.98224239, 0.85613963, 0.24027185]],

       [[0.24161421, 0.39170291, 0.77377902],
        [0.86591403, 0.81181975, 0.15940457]],

       [[0.17239481, 0.00380608, 0.3906681 ],
        [0.69063163, 0.35514608, 0.38352119]]])

In [26]:
np.random.random_sample(a.shape)

array([[0.46821489, 0.34745115, 0.43949862, 0.03739948, 0.88123932,
        0.22475016],
       [0.51597538, 0.05451825, 0.3935532 , 0.09950448, 0.05807322,
        0.71894718]])

In [37]:
np.random.randint(7,size=(4,4))

array([[1, 5, 6, 4],
       [5, 3, 3, 3],
       [2, 5, 1, 5],
       [4, 1, 2, 6]])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
c=np.array([[1,2,3]])
r1=np.repeat(c,3,axis=1)
print(r1)
r2=np.repeat(c,3,axis=0)
print(r2)

[[1 1 1 2 2 2 3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
